[package]
name = "update"
version = "0.1.0"
authors = ["Vit Spinka <spinka@pythian.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
